spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351655468576D5A7134743777217A25432A46
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# CORS
spring.web.cors.allowed-origins=http://localhost:4200

# Stripe
stripe.secret-key=sk_test_51TOLpEEDdBF3XfJJxOK3aX8mFUR9bDEKMDREujCipZTlJeSiKxsScAEm7BaVX38kXWVhjbZoatO1ybGbTxs85hnk0064vYv1fc
stripe.success-url=http://localhost:4200/orders?stripe_session_id={CHECKOUT_SESSION_ID}&stripe_status=success
stripe.cancel-url=http://localhost:4200/orders?stripe_session_id={CHECKOUT_SESSION_ID}&stripe_status=cancel
