"""LangGraph state machine wiring the agents from section 5.4 of the project spec.

In step 2 the graph stops after SQL generation — it returns the SQL preview to
the caller without executing it. Steps 4-6 will add: sanitizer, executor, analysis,
visualization.
"""
from typing import Optional, TypedDict

from langgraph.graph import StateGraph, START, END

from .agents import guardrails, sql as sql_agent
from .llm import get_chat_model
from .schema import (
    ChatRequest, ChatResponse, Classification, DataRow, Guardrail, Role,
)


class GraphState(TypedDict, total=False):
    question: str
    role: Role
    user_id: int
    store_owner_id: Optional[int]
    first_name: Optional[str]
    classification: Classification
    trigger: str
    sql_preview: str
    response: ChatResponse


_LLM = get_chat_model()


def _scope_label(role: Role) -> str:
    return {"ADMIN": "platform", "CORPORATE": "store", "INDIVIDUAL": "account"}[role]


def node_guardrails(state: GraphState) -> GraphState:
    cls, trig = guardrails.classify(_LLM, state["question"])
    state["classification"] = cls
    state["trigger"] = trig
    return state


def node_greeting(state: GraphState) -> GraphState:
    name = state.get("first_name") or "there"
    state["response"] = ChatResponse(
        status="GREETING",
        narrative=(
            f"Hi {name} — I can answer questions about your "
            f"{_scope_label(state['role'])} data. Try one of the suggested questions below."
        ),
    )
    return state


def node_blocked(state: GraphState) -> GraphState:
    state["response"] = ChatResponse(
        status="BLOCKED",
        narrative=(
            "This message tripped the safety filters. Attempts to alter the "
            "system prompt are blocked and logged."
        ),
        guardrail=Guardrail(
            type="Prompt Injection",
            trigger=f'"{state["trigger"]}"',
            action="Request fully rejected",
        ),
    )
    return state


def node_out_of_scope(state: GraphState) -> GraphState:
    state["response"] = ChatResponse(
        status="OUT_OF_SCOPE",
        narrative=(
            "That's outside what I can help with. I focus on your sales, "
            "products, orders, customers, shipments, and reviews."
        ),
        guardrail=Guardrail(
            type="Out of scope",
            trigger=state["trigger"],
            action="No SQL generated",
        ),
    )
    return state


def node_sql(state: GraphState) -> GraphState:
    state["sql_preview"] = sql_agent.generate_sql(_LLM, state["question"], state["role"])
    return state


def node_finalize_answer(state: GraphState) -> GraphState:
    """Step 2: return the SQL preview with placeholder rows + bar chart.

    Real execution lands in step 5; this node will be replaced by the executor +
    analysis agents.
    """
    sample_rows = [
        DataRow(label="Wireless Earbuds", value=284),
        DataRow(label="Smart Watch", value=217),
        DataRow(label="Bluetooth Speaker", value=196),
        DataRow(label="Mechanical Keyboard", value=178),
        DataRow(label="USB-C Hub", value=143),
    ]
    state["response"] = ChatResponse(
        status="ANSWER",
        narrative=(
            f"Here's the answer for your {_scope_label(state['role'])} data. "
            "(SQL generated by the agent — execution arrives in step 5.)"
        ),
        sql_preview=state["sql_preview"],
        rows=sample_rows,
        chart_type="BAR",
    )
    return state


def _route_after_guardrails(state: GraphState) -> str:
    cls = state["classification"]
    if cls == "prompt_injection":
        return "blocked"
    if cls == "greeting":
        return "greeting"
    if cls == "out_of_scope":
        return "out_of_scope"
    return "sql"


def build_graph():
    g = StateGraph(GraphState)
    g.add_node("guardrails", node_guardrails)
    g.add_node("greeting", node_greeting)
    g.add_node("blocked", node_blocked)
    g.add_node("out_of_scope", node_out_of_scope)
    g.add_node("sql", node_sql)
    g.add_node("finalize_answer", node_finalize_answer)

    g.add_edge(START, "guardrails")
    g.add_conditional_edges("guardrails", _route_after_guardrails, {
        "greeting": "greeting",
        "blocked": "blocked",
        "out_of_scope": "out_of_scope",
        "sql": "sql",
    })
    g.add_edge("sql", "finalize_answer")
    g.add_edge("greeting", END)
    g.add_edge("blocked", END)
    g.add_edge("out_of_scope", END)
    g.add_edge("finalize_answer", END)

    return g.compile()


_GRAPH = build_graph()


def run(req: ChatRequest) -> ChatResponse:
    initial: GraphState = {
        "question": req.question,
        "role": req.role,
        "user_id": req.user_id,
        "store_owner_id": req.store_owner_id,
        "first_name": req.first_name,
    }
    final = _GRAPH.invoke(initial)
    return final["response"]
